version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - ~/jenkins:/var/jenkins_home
    restart: always
    ports:
      - 8080:8080

  server:
    image: nginx:1.17.2
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # your nginx config file
      - /var/log/nginx:/var/log/nginx # log files
    restart: always
    command: nginx-debug -g 'daemon off;'
    ports:
      - 8000:80

    depends_on:
      - jenkins

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:latest
    ports:
      - 4444:4444
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443


  selenium-node-chrome:
    container_name: selenium-node-chrome
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub

    ports:
      - 5900:5900
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  selenium-node-firefox:
    container_name: selenium-node-firefox
    image: selenium/node-firefox:latest
    depends_on:
      - selenium-hub
    ports:
      - 5901:5901
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
