version: "3"
services:

  chrome:
        platform: linux/amd64
        image: selenium/node-chrome
        container_name: chrome
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=2
            - NODE_MAX_SESSION=2


  firefox:
        image: selenium/node-firefox
        platform: linux/amd64
        container_name: firefox
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444

  selenium-hub:
    platform: linux/amd64
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:4444/grid/api/proxy" ]
      interval: 10s
      timeout: 5s
      retries: 3
